import "../public/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quick Dart Request",
  description: "Generated by create next app",
  icons: "logo.ico",
  authors: [
    { name: "Diego Arturo Yangua Merino", url: "https://github.com/Dacyz" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ overflowX: "hidden" }}>
        {children}
      </body>
    </html>
  );
}
